version: "3.8"

services:

  postgresqldb:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    restart: always
    ports: 
      - "5432:5432"
    links:
      - pgadmin



  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    restart: always
    ports:
      - "80:80"

